removed package check

diff --git a/clyde b/clyde
--- a/clyde
+++ b/clyde
@@ -14,10 +14,10 @@ then
 	cd $CLYDE_TMP
 
 	# Check if package exists
-	if ! curl -s --head  --request GET ${URL} | grep "404 Not Found" > /dev/null
-	then
-	       echo "Package ${PACKAGE} not found"
-	fi
+	#if ! curl -s --head  --request GET ${URL} | grep "404 Not Found" > /dev/null
+	#then
+	#       echo "Package ${PACKAGE} not found"
+	#fi
 	else
 		read -p "Install ${PACKAGE}? [y/N]: " $OPTION
 		if [ $OPTION = "n" || $OPTION = "N" ]
